/**
 * Sandbox AI-Assisted Check-In -- Canonical Script & Fixed Templates
 *
 * Question order and every escalation/closing message are deterministic and
 * defined here -- never generated by the LLM. Clinical source: HEARTLAND
 * Protocol v3.3, Module 5, Section 5.2 (reference/clinical_content.md) and
 * RED_FLAG_CRITERIA in lib/vitals/constants.ts.
 */

import type { RedFlag } from '@/lib/vitals/types';
import type { CheckInExtraction, ScriptQuestion, ScriptQuestionId } from './types';

export const SCRIPT_QUESTIONS: Record<ScriptQuestionId, ScriptQuestion> = {
  q1_safety: {
    id: 'q1_safety',
    canonical:
      'First, the important one: any chest pain, or have you fainted or almost fainted since yesterday?',
    extractionKeys: ['chestPainOrSyncope'],
    skippable: false,
  },
  q2_weight: {
    id: 'q2_weight',
    canonical: 'What did the scale show this morning, in pounds?',
    extractionKeys: ['weightLbs'],
    skippable: false,
  },
  q3_breathing: {
    id: 'q3_breathing',
    canonical:
      'How is your breathing today — fine, short of breath with activity, or short of breath even at rest?',
    extractionKeys: ['dyspnea'],
    skippable: false,
  },
  q4_swelling: {
    id: 'q4_swelling',
    canonical: 'Any new or worse swelling in your feet, ankles, or legs?',
    extractionKeys: ['edema'],
    skippable: false,
  },
  q5_orthopnea: {
    id: 'q5_orthopnea',
    canonical:
      'Last night, did you need extra pillows — or to sit up — to breathe while sleeping?',
    extractionKeys: ['orthopnea'],
    skippable: false,
  },
  q6_fatigue: {
    id: 'q6_fatigue',
    canonical: 'How is your energy today compared to normal?',
    extractionKeys: ['fatigue'],
    skippable: false,
  },
  q7_adherence: {
    id: 'q7_adherence',
    canonical: 'Were you able to take all of your medicines yesterday and today?',
    extractionKeys: ['adherence'],
    skippable: false,
  },
  q8_devices: {
    id: 'q8_devices',
    canonical:
      "If you have a blood pressure cuff or oxygen meter at home, what were the numbers? It's fine to skip this.",
    extractionKeys: ['sbp', 'spo2'],
    skippable: true,
  },
};

export const QUESTION_ORDER: readonly ScriptQuestionId[] = [
  'q1_safety',
  'q2_weight',
  'q3_breathing',
  'q4_swelling',
  'q5_orthopnea',
  'q6_fatigue',
  'q7_adherence',
  'q8_devices',
];

export function nextQuestionId(current: ScriptQuestionId): ScriptQuestionId | null {
  const index = QUESTION_ORDER.indexOf(current);
  return index >= 0 && index < QUESTION_ORDER.length - 1 ? QUESTION_ORDER[index + 1] : null;
}

const DEMO_NOTE = '[Demonstration environment — synthetic data, no real call or alert is placed.]';

export const INTRO_MESSAGES: readonly string[] = [
  "Hi! This is the automated daily check-in from your heart care team. I collect a few quick answers and a member of your care team reviews everything — I never make medical decisions. This takes about 2 minutes.",
  SCRIPT_QUESTIONS.q1_safety.canonical,
];

export const EMERGENCY_911_MESSAGE =
  'Thank you for telling me. Chest pain or fainting needs immediate attention. This ends the automated check-in and alerts your care team right now. In a real deployment: call 911 or your local emergency number immediately. ' +
  DEMO_NOTE;

export const DEFLECT_MESSAGE =
  "I can't give medical advice — I only collect your daily check-in so your care team can review it. If you're worried, contact your care team; for an emergency, call 911. Now, back to the check-in:";

export const FALLBACK_NOTICE =
  'The conversational assistant is unavailable right now — please use this quick form instead. Red-flag checks work exactly the same way.';

export function escalationMessage(flags: RedFlag[]): string {
  const detail = flags.map((flag) => `${flag.message} — ${flag.action}.`).join(' ');
  return (
    `Thank you. Based on your care plan's preset rules, what you reported needs review: ${detail} ` +
    'A member of your care team is being notified and will call you today. ' +
    DEMO_NOTE
  );
}

const DYSPNEA_LABELS = ['fine', 'short of breath with heavy activity', 'short of breath with activity', 'short of breath at rest'] as const;
const SEVERITY_LABELS = ['none', 'mild', 'moderate', 'severe'] as const;
const ADHERENCE_LABELS = { yes: 'all taken', missed_some: 'missed some', no: 'not taken' } as const;

export function recordedSummary(extraction: CheckInExtraction): string {
  const parts = [
    `weight ${extraction.weightLbs !== null ? `${extraction.weightLbs} lbs` : 'not recorded'}`,
    `breathing: ${extraction.dyspnea !== null ? DYSPNEA_LABELS[extraction.dyspnea] : 'not recorded'}`,
    `swelling: ${extraction.edema !== null ? SEVERITY_LABELS[extraction.edema] : 'not recorded'}`,
    `sleep: ${extraction.orthopnea === null ? 'not recorded' : extraction.orthopnea ? 'needed extra pillows' : 'no extra pillows needed'}`,
    `energy: ${extraction.fatigue !== null ? `${SEVERITY_LABELS[extraction.fatigue]} fatigue` : 'not recorded'}`,
    `medicines: ${extraction.adherence !== null ? ADHERENCE_LABELS[extraction.adherence] : 'not recorded'}`,
    `blood pressure: ${extraction.sbp !== null ? `${extraction.sbp} mmHg systolic` : 'skipped'}`,
    `oxygen: ${extraction.spo2 !== null ? `${extraction.spo2}%` : 'skipped'}`,
  ];
  return `Here is what I recorded for your care team: ${parts.join(' · ')}.`;
}

export function routineClosingMessage(extraction: CheckInExtraction): string {
  return (
    `${recordedSummary(extraction)} Your care team will see this summary. ` +
    "Nothing you reported needs urgent attention according to your care plan's preset rules. " +
    'If anything changes or worries you, contact your care team — and for an emergency, call 911. ' +
    DEMO_NOTE
  );
}

// ── Spoken lines for the simulated live call (fixed; pre-generated audio) ──

export const SPOKEN_CALL_INTRO =
  "Hi, this is the automated daily check-in call from your heart care team. A member of your care team reviews everything I collect — I never make medical decisions. This takes about two minutes.";

export const SPOKEN_ESCALATION =
  "Thank you. Based on your care plan's preset rules, what you reported today needs a closer look. I'm flagging it for your care team right now, and a nurse will call you back today — please keep your phone nearby. If anything suddenly gets worse before then, call 911. Take care, and we'll talk soon. Bye-bye.";

export const SPOKEN_ROUTINE =
  "Thank you — that's everything I need today. Nothing you reported needs urgent attention according to your care plan's preset rules, and your care team will see the full summary. Same time tomorrow? Take care. Bye-bye.";

export const SPOKEN_EMERGENCY =
  "Thank you for telling me. Chest pain or fainting needs immediate attention, so this ends the automated check-in and alerts your care team right now. In a real deployment: call 911 or your local emergency number immediately.";

export const SPOKEN_DEFLECT =
  "I can't give medical advice — I only collect your daily check-in so your care team can review it. If you're worried, contact your care team, and for an emergency call 911. Now, back to the check-in.";
