/**
 * Sandbox AI-Assisted Check-In -- Canonical Script & Fixed Templates
 *
 * Question order and every escalation/closing message are deterministic and
 * defined here -- never generated by the LLM. Clinical source: HEARTLAND
 * Protocol v3.3, Module 5, Section 5.2 (reference/clinical_content.md) and
 * RED_FLAG_CRITERIA in lib/vitals/constants.ts.
 */

import type { RedFlag } from '@/lib/vitals/types';
import type { CallLocale, CheckInExtraction, ScriptQuestion, ScriptQuestionId } from './types';

export const SCRIPT_QUESTIONS: Record<string, ScriptQuestion> = {
  q1_safety: {
    id: 'q1_safety',
    canonical:
      'First, the important one: any chest pain, or have you fainted or almost fainted since yesterday?',
    canonicalEs:
      'Primero, lo importante: ¿algún dolor de pecho, o se ha desmayado o casi desmayado desde ayer?',
    extractionKeys: ['chestPainOrSyncope'],
    skippable: false,
  },
  q2_weight: {
    id: 'q2_weight',
    canonical: 'What did the scale show this morning, in pounds?',
    canonicalEs: '¿Qué mostró la báscula esta mañana, en libras?',
    extractionKeys: ['weightLbs'],
    skippable: false,
  },
  q3_breathing: {
    id: 'q3_breathing',
    canonical:
      'How is your breathing today — fine, short of breath with activity, or short of breath even at rest?',
    canonicalEs:
      '¿Cómo está su respiración hoy — bien, con falta de aire al hacer actividad, o con falta de aire incluso en reposo?',
    extractionKeys: ['dyspnea'],
    skippable: false,
  },
  q4_swelling: {
    id: 'q4_swelling',
    canonical: 'Any new or worse swelling in your feet, ankles, or legs?',
    canonicalEs: '¿Alguna hinchazón nueva o peor en los pies, los tobillos o las piernas?',
    extractionKeys: ['edema'],
    skippable: false,
  },
  q5_orthopnea: {
    id: 'q5_orthopnea',
    canonical:
      'Last night, did you need extra pillows — or to sit up — to breathe while sleeping?',
    canonicalEs:
      'Anoche, ¿necesitó almohadas adicionales — o sentarse — para poder respirar mientras dormía?',
    extractionKeys: ['orthopnea'],
    skippable: false,
  },
  q6_fatigue: {
    id: 'q6_fatigue',
    canonical: 'How is your energy today compared to normal?',
    canonicalEs: '¿Cómo está su energía hoy comparada con lo normal?',
    extractionKeys: ['fatigue'],
    skippable: false,
  },
  q7_adherence: {
    id: 'q7_adherence',
    canonical: 'Were you able to take all of your medicines yesterday and today?',
    canonicalEs: '¿Pudo tomar todas sus medicinas ayer y hoy?',
    extractionKeys: ['adherence'],
    skippable: false,
  },
  q8_devices: {
    id: 'q8_devices',
    canonical:
      "If you have a blood pressure cuff or oxygen meter at home, what were the numbers? It's fine to skip this.",
    canonicalEs:
      'Si tiene en casa un tensiómetro o un medidor de oxígeno, ¿cuáles fueron los números? Está bien saltarse esta.',
    extractionKeys: ['sbp', 'spo2'],
    skippable: true,
  },
};

export const QUESTION_ORDER: readonly ScriptQuestionId[] = [
  'q1_safety',
  'q2_weight',
  'q3_breathing',
  'q4_swelling',
  'q5_orthopnea',
  'q6_fatigue',
  'q7_adherence',
  'q8_devices',
];

export function nextQuestionId(current: ScriptQuestionId): ScriptQuestionId | null {
  const index = QUESTION_ORDER.indexOf(current);
  return index >= 0 && index < QUESTION_ORDER.length - 1 ? QUESTION_ORDER[index + 1] : null;
}

// Plain text is shared with speech; brackets may be interpreted as audio tags.
const DEMO_NOTE = 'Synthetic demo: no real calls, alerts, notifications, or appointments.';
const DEMO_NOTE_ES = 'Demostración sintética: sin llamadas, alertas, notificaciones ni citas reales.';

export function demoNoteFor(locale: CallLocale): string {
  return locale === 'es' ? DEMO_NOTE_ES : DEMO_NOTE;
}

export const INTRO_MESSAGES: readonly string[] = [
  `Hi! This is a simulated daily check-in. I collect and structure answers — I never make medical decisions. Clinical decisions require human review. ${DEMO_NOTE}`,
  SCRIPT_QUESTIONS.q1_safety.canonical,
];

export const INTRO_MESSAGES_ES: readonly string[] = [
  `¡Hola! Este es un chequeo diario simulado. Recojo y organizo respuestas — yo nunca tomo decisiones médicas. Las decisiones clínicas requieren revisión humana. ${DEMO_NOTE_ES}`,
  SCRIPT_QUESTIONS.q1_safety.canonicalEs,
];

export function introMessagesFor(locale: CallLocale): readonly string[] {
  return locale === 'es' ? INTRO_MESSAGES_ES : INTRO_MESSAGES;
}

export const EMERGENCY_911_MESSAGE =
  'Thank you for telling me. Chest pain or fainting needs immediate attention. This ends the simulated check-in. If you are experiencing these symptoms, call 911 or your local emergency number immediately. Do not wait for this demo or a care-team callback. ' +
  DEMO_NOTE;

export const EMERGENCY_911_MESSAGE_ES =
  'Gracias por decírmelo. El dolor de pecho o los desmayos necesitan atención inmediata. Esto termina el chequeo simulado. Si está experimentando estos síntomas, llame al 911 o a su número local de emergencias de inmediato. No espere a esta demostración ni una llamada de su equipo de atención. ' +
  DEMO_NOTE_ES;

export function emergencyMessageFor(locale: CallLocale): string {
  return locale === 'es' ? EMERGENCY_911_MESSAGE_ES : EMERGENCY_911_MESSAGE;
}

export const DEFLECT_MESSAGE =
  `I can't give medical advice — I only collect and structure answers in this demo. Clinical decisions require human review. If you're worried, contact your care team; for an emergency, call 911. ${DEMO_NOTE} Now, back to the check-in:`;

export const DEFLECT_MESSAGE_ES =
  `No puedo dar consejos médicos — solo recojo y organizo respuestas en esta demostración. Las decisiones clínicas requieren revisión humana. Si está preocupado o preocupada, comuníquese con su equipo de atención; en una emergencia, llame al 911. ${DEMO_NOTE_ES} Ahora, volvamos al chequeo:`;

export function deflectMessageFor(locale: CallLocale): string {
  return locale === 'es' ? DEFLECT_MESSAGE_ES : DEFLECT_MESSAGE;
}

export const FALLBACK_NOTICE =
  'The conversational assistant is unavailable right now — please use this quick form instead. Red-flag checks work exactly the same way.';

export const FALLBACK_NOTICE_ES =
  'El asistente conversacional no está disponible en este momento — por favor use este formulario rápido. Las verificaciones de señales de alerta funcionan exactamente igual.';

export function fallbackNoticeFor(locale: CallLocale): string {
  return locale === 'es' ? FALLBACK_NOTICE_ES : FALLBACK_NOTICE;
}

export function escalationMessage(flags: RedFlag[], locale: CallLocale = 'en'): string {
  // Registered rule texts (message/action) are quoted verbatim in every locale.
  const detail = flags.map((flag) => `${flag.message} — ${flag.action}.`).join(' ');
  if (locale === 'es') {
    return (
      `Gracias. Las reglas preestablecidas requieren revisión humana de este caso sintético: ${detail} ` +
      'La demostración estructura el resumen, pero no realiza la revisión ni el seguimiento. En una emergencia, llame al 911 sin esperar a esta demostración. ' +
      DEMO_NOTE_ES
    );
  }
  return (
    `Thank you. The preset rules require human review of this synthetic case: ${detail} ` +
    'The demo structures the summary but does not provide review or follow-up. For an emergency, call 911 without waiting for this demo. ' +
    DEMO_NOTE
  );
}

const DYSPNEA_LABELS = ['fine', 'short of breath with heavy activity', 'short of breath with activity', 'short of breath at rest'] as const;
const SEVERITY_LABELS = ['none', 'mild', 'moderate', 'severe'] as const;
const ADHERENCE_LABELS = { yes: 'all taken', missed_some: 'missed some', no: 'not taken' } as const;
const DYSPNEA_LABELS_ES = ['bien', 'falta de aire con actividad intensa', 'falta de aire con actividad', 'falta de aire en reposo'] as const;
const SEVERITY_LABELS_ES = ['ninguna', 'leve', 'moderada', 'grave'] as const;
const ADHERENCE_LABELS_ES = { yes: 'todas tomadas', missed_some: 'faltaron algunas', no: 'no tomadas' } as const;

export function recordedSummary(extraction: CheckInExtraction, locale: CallLocale = 'en'): string {
  if (locale === 'es') {
    const parts = [
      `peso ${extraction.weightLbs !== null ? `${extraction.weightLbs} libras` : 'no registrado'}`,
      `respiración: ${extraction.dyspnea !== null ? DYSPNEA_LABELS_ES[extraction.dyspnea] : 'no registrada'}`,
      `hinchazón: ${extraction.edema !== null ? SEVERITY_LABELS_ES[extraction.edema] : 'no registrada'}`,
      `sueño: ${extraction.orthopnea === null ? 'no registrado' : extraction.orthopnea ? 'necesitó almohadas adicionales' : 'sin almohadas adicionales'}`,
      `energía: ${extraction.fatigue !== null ? `fatiga ${SEVERITY_LABELS_ES[extraction.fatigue]}` : 'no registrada'}`,
      `medicinas: ${extraction.adherence !== null ? ADHERENCE_LABELS_ES[extraction.adherence] : 'no registrado'}`,
      `presión arterial: ${extraction.sbp !== null ? `${extraction.sbp} mmHg sistólica` : 'omitida'}`,
      `oxígeno: ${extraction.spo2 !== null ? `${extraction.spo2}%` : 'omitido'}`,
    ];
    return `Resumen estructurado de este caso sintético: ${parts.join(' · ')}.`;
  }
  const parts = [
    `weight ${extraction.weightLbs !== null ? `${extraction.weightLbs} lbs` : 'not recorded'}`,
    `breathing: ${extraction.dyspnea !== null ? DYSPNEA_LABELS[extraction.dyspnea] : 'not recorded'}`,
    `swelling: ${extraction.edema !== null ? SEVERITY_LABELS[extraction.edema] : 'not recorded'}`,
    `sleep: ${extraction.orthopnea === null ? 'not recorded' : extraction.orthopnea ? 'needed extra pillows' : 'no extra pillows needed'}`,
    `energy: ${extraction.fatigue !== null ? `${SEVERITY_LABELS[extraction.fatigue]} fatigue` : 'not recorded'}`,
    `medicines: ${extraction.adherence !== null ? ADHERENCE_LABELS[extraction.adherence] : 'not recorded'}`,
    `blood pressure: ${extraction.sbp !== null ? `${extraction.sbp} mmHg systolic` : 'skipped'}`,
    `oxygen: ${extraction.spo2 !== null ? `${extraction.spo2}%` : 'skipped'}`,
  ];
  return `Structured summary of this synthetic case: ${parts.join(' · ')}.`;
}

export function routineClosingMessage(extraction: CheckInExtraction, locale: CallLocale = 'en'): string {
  if (locale === 'es') {
    return (
      `${recordedSummary(extraction, 'es')} ` +
      'Nada de lo que reportó necesita atención urgente según las reglas preestablecidas. Esto no es una evaluación clínica; toda decisión clínica requiere revisión humana. ' +
      'Si algo cambia o le preocupa, contacte a su equipo de atención — y en una emergencia, llame al 911. ' +
      DEMO_NOTE_ES
    );
  }
  return (
    `${recordedSummary(extraction)} ` +
    'Nothing you reported needs urgent attention according to the preset rules. This is not a clinical assessment; human review is required for any clinical decision. ' +
    'If anything changes or worries you, contact your care team — and for an emergency, call 911. ' +
    DEMO_NOTE
  );
}

// ── Spoken lines for the simulated live call (fixed; pre-generated audio) ──

export const SPOKEN_CALL_INTRO =
  `Hi, this is a simulated daily check-in. I collect and structure answers — I never make medical decisions. Clinical decisions require human review. ${DEMO_NOTE}`;

export const SPOKEN_ESCALATION =
  `Thank you. Preset rules require human review of this case. I structure the summary; no review or follow-up occurs here. If anything suddenly gets worse, call 911 without waiting for this demo. ${DEMO_NOTE} Goodbye.`;

export const SPOKEN_ROUTINE =
  `Thank you. No urgent flags were found by the preset rules for this case. Clinical decisions still require human review. Contact your care team if concerned; for an emergency, call 911. ${DEMO_NOTE} Goodbye.`;

export const SPOKEN_EMERGENCY =
  EMERGENCY_911_MESSAGE;

export const SPOKEN_DEFLECT =
  DEFLECT_MESSAGE;

// Spanish spoken lines require bilingual review before regenerated audio is released.

export const SPOKEN_CALL_INTRO_ES =
  `Hola, este es un chequeo diario simulado. Recojo y organizo respuestas — yo nunca tomo decisiones médicas. Las decisiones clínicas requieren revisión humana. ${DEMO_NOTE_ES}`;

export const SPOKEN_ESCALATION_ES =
  `Gracias. Las reglas preestablecidas requieren revisión humana de este caso. Organizo el resumen; aquí no se realiza la revisión ni el seguimiento. Si algo empeora de repente, llame al 911 sin esperar a esta demostración. ${DEMO_NOTE_ES} Adiós.`;

export const SPOKEN_ROUTINE_ES =
  `Gracias. Las reglas preestablecidas no detectaron alertas urgentes en este caso. Las decisiones clínicas aún requieren revisión humana. Si algo le preocupa, contacte a su equipo; en una emergencia, llame al 911. ${DEMO_NOTE_ES} Adiós.`;

export const SPOKEN_EMERGENCY_ES =
  EMERGENCY_911_MESSAGE_ES;

export const SPOKEN_DEFLECT_ES =
  DEFLECT_MESSAGE_ES;

/** Short spoken acknowledgments played while the server processes a voice turn. */
export const FILLER_LINES: Record<CallLocale, readonly string[]> = {
  en: ['Mm-hm, let me note that down.', 'Okay, one moment.', 'Got it, thank you.'],
  es: ['Ajá, déjeme anotar eso.', 'Bien, un momento.', 'Entendido, gracias.'],
};
