/**
 * MonthlyReportPrint -- Print Layout
 *
 * Hidden on screen, visible when printing. Contains the full monthly
 * usage report with HEARTLAND header, metrics table, and clinical disclaimer.
 *
 * Requirement: REPT-01 (Monthly Panel Report)
 * Pattern: hidden print:block (from titration-checklist/print-layout.tsx)
 */

import React from 'react';
import type { MonthlyReportData } from '@/lib/reports/types';

interface MonthlyReportPrintProps {
  data: MonthlyReportData;
}

export const MonthlyReportPrint = React.forwardRef<
  HTMLDivElement,
  MonthlyReportPrintProps
>(function MonthlyReportPrint({ data }, ref) {
  return (
    <div ref={ref} className="hidden print:block p-8 text-sm font-sans" data-testid="monthly-report-print">
      {/* Header */}
      <h1 className="text-xl font-bold mb-1">HEARTLAND Monthly Usage Report</h1>
      <p className="text-sm text-gray-600 mb-4">
        Period: {data.from} &ndash; {data.to}
      </p>

      {/* Disclaimer */}
      <p className="text-xs italic border p-2 mb-6">
        This tool is designed for healthcare professionals as a clinical decision support resource.
        It does not provide medical diagnoses, treatment recommendations for individual patients,
        or replace clinical judgment. Not intended for direct patient care. For professional use only.
      </p>

      {/* Metrics table */}
      <table className="w-full text-sm mb-6 border-collapse">
        <thead>
          <tr className="border-b">
            <th className="py-2 text-left font-semibold">Metric</th>
            <th className="py-2 text-left font-semibold">Value</th>
          </tr>
        </thead>
        <tbody>
          <tr className="border-b border-gray-200">
            <td className="py-2">Patients Monitored</td>
            <td className="py-2">{data.totalPatients}</td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-2">Active in Period</td>
            <td className="py-2">{data.activePatientsInPeriod}</td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-2">Alerts Generated</td>
            <td className="py-2">{data.alertsGenerated}</td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-2">Critical Alerts</td>
            <td className="py-2">{data.alertsCritical}</td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-2">Titrations Completed</td>
            <td className="py-2">{data.titrationNotesCount}</td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-2">Check-In Compliance</td>
            <td className="py-2">{data.avgCheckInCompliance.toFixed(1)}%</td>
          </tr>
          <tr className="border-b border-gray-200">
            <td className="py-2">GDMT Optimization Rate</td>
            <td className="py-2">
              {data.gdmtOptimizationRate !== null
                ? `${data.gdmtOptimizationRate.toFixed(1)}%`
                : 'Pending (Phase 13)'}
            </td>
          </tr>
        </tbody>
      </table>

      {/* Explanatory note */}
      <p className="text-xs italic text-gray-500 mb-6">
        Titrations completed = titration notes saved in app. May differ from GA4 event counts.
      </p>

      {/* Footer */}
      <p className="text-xs text-gray-400 border-t pt-2">
        Generated by HEARTLAND Protocol App &mdash; app.heartlandprotocol.org &mdash;{' '}
        {new Date().toLocaleDateString()}
      </p>
    </div>
  );
});
